[package]
name = "yup"
version = "0.1.4"
edition = "2024"
authors = ["izantech"]
description = "One command to update packages across all your managers."
license = "MIT"
repository = "https://github.com/izantech/yup"
keywords = ["cli", "update", "package-manager", "devtools"]
categories = ["command-line-utilities", "development-tools"]

[package.metadata.oxide]

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
dialoguer = "0.12.0"
indicatif = { version = "0.18.3", features = ["tokio"] }
directories = "6.0.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["rt", "macros", "sync", "time", "io-util", "process"] }
toml = "0.9.11"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
tracing-appender = "0.2.4"
strum = { version = "0.27.2", features = ["derive"] }
which = "8.0.0"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
